"""initial schema

Revision ID: 8013dd4738f9
Revises: 
Create Date: 2026-03-05 05:26:04.182654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8013dd4738f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_daily_scan', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_url', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scan_status', sa.String(length=50), nullable=True),
    sa.Column('scan_message', sa.String(length=200), nullable=True),
    sa.Column('last_scan_date', sa.DateTime(), nullable=True),
    sa.Column('current_task_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('out_of_scope', sa.Text(), nullable=True),
    sa.Column('in_scope', sa.Text(), nullable=True),
    sa.Column('discovery_enabled', sa.Boolean(), nullable=True),
    sa.Column('fuzzing_enabled', sa.Boolean(), nullable=True),
    sa.Column('vuln_scan_enabled', sa.Boolean(), nullable=True),
    sa.Column('vuln_scan_recon_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('scanned_vulns', sa.Boolean(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('open_ports', sa.Text(), nullable=True),
    sa.Column('dns_info', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('discovered_paths', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index('ix_domain_project_first_seen', ['project_id', 'first_seen'], unique=False)
        batch_op.create_index('ix_domain_project_scanned', ['project_id', 'scanned_vulns'], unique=False)
        batch_op.create_index('ix_domain_project_status', ['project_id', 'status_code'], unique=False)

    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('new_domains', sa.Integer(), nullable=True),
    sa.Column('total_domains', sa.Integer(), nullable=True),
    sa.Column('alive_hosts', sa.Integer(), nullable=True),
    sa.Column('new_vulns', sa.Integer(), nullable=True),
    sa.Column('total_vulns', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.create_index('ix_scan_history_project_started', ['project_id', 'started_at'], unique=False)

    op.create_table('port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'port_number', name='uq_domain_port')
    )
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.create_index('ix_port_number', ['port_number'], unique=False)

    op.create_table('vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability')
    with op.batch_alter_table('port', schema=None) as batch_op:
        batch_op.drop_index('ix_port_number')

    op.drop_table('port')
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_history_project_started')

    op.drop_table('scan_history')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index('ix_domain_project_status')
        batch_op.drop_index('ix_domain_project_scanned')
        batch_op.drop_index('ix_domain_project_first_seen')

    op.drop_table('domain')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('system_state')
    # ### end Alembic commands ###
